samples_dir: "/pfss/mlde/workspaces/mlde_wsp_Rohrbach/users/ns94feza/large_language_monkeys/llmonk/outputs/math128/Llama-3.3-70B-Instruct"
verifications_dir: "/pfss/mlde/workspaces/mlde_wsp_Rohrbach/users/ns94feza/large_language_monkeys/llmonk/outputs/verifications/math128/Llama-3.3-70B-Instruct/ver_model--Llama-3.3-70B-Instruct__max_tokens--4096"
all_num_solutions_plot: [1, 2, 4, 8, 16, 32, 64, 128, 256]
all_num_solutions_plot_no_verif: [1, 2, 4, 8, 16, 32, 64, 128, 256]
all_num_verifications_plot: [1, 2, 4, 8, 16, 32]
plot_save_dir: "plots_new/math128/Llama-3.3-70B-Instruct/ver_model--Llama-3.3-70B-Instruct__max_tokens--4096"

num_problems: 120
max_num_solutions_without_verifs: 256
max_num_solutions_with_verifs: 256
max_num_verifications: 32
math_type: "minerva"
plot_title: "MATH128 Llama 3.3 70B GenRM-Base"
lamb: 1.0
model: 'llama70b'

use_hybrid: false
use_verification_logprobs: false
recompute: true
best_of_n: true
majority_voting: true
fix_num_verifications: true